[project]
name = "dagster-dataframely"
version = "0.0.1"
description = "A Dataframely plugin for Dagster."
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [{ name = "Ozan Ozbeker", email = "github@ozanozbeker.com" }]
maintainers = [{ name = "Ozan Ozbeker", email = "github@ozanozbeker.com" }]
keywords = [
  "dagster",
  "data",
  "data-quality",
  "dataframely",
  "polars",
  "validation",
]
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Database",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]
dependencies = [
  "dagster>=1.13.16",
  "dataframely>=3.0.0",
  "polars>=1.43.2",
]

[project.urls]
Homepage = "https://github.com/ozanozbeker/dagster-dataframely"
Repository = "https://github.com/ozanozbeker/dagster-dataframely"
Issues = "https://github.com/ozanozbeker/dagster-dataframely/issues"
Changelog = "https://github.com/ozanozbeker/dagster-dataframely/releases"

[dependency-groups]
dev = [
  "dagster-graphql>=1.13.16",
  "dagster-webserver>=1.13.16",
  "prek>=0.4.12",
  "pytest>=9.1.1",
  "ruff>=0.16.1",
  "rumdl>=0.2.50",
  "ty>=0.0.66",
]

[build-system]
requires = ["uv_build>=0.12.00,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = ["-ra", "--strict-config", "--strict-markers"]
testpaths = ["tests"]
